In [2]:
import numpy as np

arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
arr3=np.zeros((3,4))
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.full((4,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [12]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.arange(1,99,11)

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [20]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [25]:
arr=np.array([[1,2,3],[4,5,6],[5,6,7],[5,6,7],[9,8,7]],dtype='float32')
print("array shape is :",arr.shape)
print("array size is :",arr.size)
print("array dimensions is :",arr.ndim)
print("array type is :",arr.dtype)

array shape is : (5, 3)
array size is : 15
array dimensions is : 2
array type is : float32


In [32]:
arr=arr.astype('float64')

In [33]:
arr.dtype


dtype('float64')

In [35]:
arr.reshape((3,5))

array([[1., 2., 3., 4., 5.],
       [6., 5., 6., 7., 5.],
       [6., 7., 9., 8., 7.]])

In [37]:
arr.flatten()

array([1., 2., 3., 4., 5., 6., 5., 6., 7., 5., 6., 7., 9., 8., 7.])

In [44]:
#indexing and slicing 
print(arr)
print(arr[1:4][2:3])

[[1. 2. 3.]
 [4. 5. 6.]
 [5. 6. 7.]
 [5. 6. 7.]
 [9. 8. 7.]]
[[5. 6. 7.]]


In [56]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)
print(arr4.shape)
print(arr4.ndim)
print(arr4.reshape(1,9))
print(arr4.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [61]:
arr5=np.array([1.1,2.2,3.3,4.4,5.5,6])
arr5=arr5.astype("int")
print(arr5)

[1 2 3 4 5 6]


In [64]:
mask=arr5%2==0
print(arr5[mask])

[2 4 6]


In [68]:
arr6=np.array([1,2,3,4,5,6,7,8,9])
arr6=arr6.reshape(3,3)
print(arr6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
